---
###############################################################################
#
# container_stopped.yml
#
# @author Arsi Atomi
#
###############################################################################

###############################################################################
# SETTING VARIABLES
###############################################################################

- name: "Checking if required variables are defined"
  ansible.builtin.assert:
    that:
      - podman_container_record is defined
      - podman_container_record.parameters is defined
      - podman_container_record.parameters.name is defined
      - podman_container_record.parameters.name is match('^[A-Za-z0-9][A-Za-z0-9_.-]*$')
    fail_msg: "All tests did not pass"

###############################################################################
# ENSURING CONTAINER IS STOPPED
###############################################################################

- name: "Checking container status"
  ansible.builtin.command:
    argv: ["podman", "inspect", "--format", "{{ '{{ .State.Status }}' }}", "{{ podman_container_record.parameters.name }}"]
  register: container_active
  changed_when: false
  failed_when: false

- name: "Ensuring container is stopped"
  ansible.builtin.command:
    argv: ["podman", "stop", "{{ podman_container_record.parameters.name }}"]
  changed_when: true
  when: container_active.stdout == "running"
