---
###############################################################################
#
# present.yml
#
# @author Arsi Atomi
#
###############################################################################

###############################################################################
# SETTING VARIABLES
###############################################################################


###############################################################################
# INSTALLING PODMAN
###############################################################################

- name: "Ensuring podman package is installed"
  ansible.builtin.include_tasks: package_present.yml
  vars:
    iac_package: "podman"

- name: "Ensuring Podman network helper packages are installed"
  ansible.builtin.include_tasks: package_present.yml
  loop:
    - "slirp4netns"
    - "passt"
  loop_control:
    loop_var: iac_package

###############################################################################
# ENSURING DEFAULT CONFIGURATION
###############################################################################

- name: "Rendering configuration lines"
  ansible.builtin.set_fact:
    rendered_lines: |
      [network]
      {% for item in podman_network_configuration | dict2items if item.value is not none %}
      {% if item.value is string %}
      {{ item.key }} = "{{ item.value }}"
      {% else %}
      {{ item.key }} = {{ item.value }}
      {% endif %}
      {% endfor %}
  when: podman_network_configuration is defined

- name: "Ensuring Podman configuration"
  ansible.builtin.copy:
    content: "{{ rendered_lines }}"
    dest: "{{ podman_containers_conf }}"
    mode: "0640"
    owner: "root"
    group: "root"
  when: rendered_lines is defined

###############################################################################
# ENSURING FILESYSTEM CONFIGURATION
###############################################################################

- name: "Ensuring filesystem configuration is present"
  ansible.builtin.include_tasks: fs_present.yml
  when: iac_blueprint.podman.directories is defined
  vars:
    iac_fs_directories: "{{ iac_blueprint.podman.directories | default([]) }}"
    iac_fs_files: "{{ iac_blueprint.podman.files | default([]) }}"

###############################################################################
# ENSURING CRONJOB CONFIGURATION
###############################################################################

- name: "Ensuring cron package is installed"
  ansible.builtin.include_tasks: package_present.yml
  when: iac_blueprint.podman.cron is defined
  vars:
    iac_package: "cronie"

- name: "Ensuring filesystem configuration is present"
  ansible.builtin.include_tasks: cron_present.yml
  when: iac_blueprint.podman.cron is defined
  vars:
    iac_cron: "{{ iac_blueprint.podman.cron | default([]) }}"
