---
servers:
  hosts:
    host.example.org:
  vars:
    iac_blueprint:
      podman:
        configuration:
          network:
            network_backend: netavark
            default_subnet: 10.168.0.0/24
            default_gateway: 10.168.0.1
        directories:
          - path: /opt/idarsi/podman
            owner: root
            group: root
            mode: "0750"
        files:
          - path: /opt/idarsi/podman/example.env
            content: |
              EXAMPLE=true
              EXAMPLE_PORT=8080
            owner: root
            group: root
            mode: "0640"
        cron:
          - name: podman_heartbeat
            user: root
            minute: "0"
            hour: "3"
            job: "/bin/true"
            cron_file: podman_heartbeat
